apiVersion: v1
kind: Pod
metadata:
  name: {{pod-name}}
  annotations:
    scheduler.alpha.kubernetes.io/name: py-scheduler
  labels:
    app: nginx
    leoregion: {{leoregion}}
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    imagePullPolicy: Always 
