apiVersion: v1
kind: Pod
metadata:
  name: nginx-iot-rig2
  namespace: default
  labels:
    app: nginx
    leoregion: '28.6657_-89.9694'
spec:
  containers:
  - name: nginx-iot-rig2
    image: vaibhavb007/nginx_iot
    ports:
    - containerPort: 80
