apiVersion: v1
kind: Pod
metadata:
  name: nginx-smokeys
  namespace: default
  labels:
    app: nginx
    leoregion: '37.7749_-122.4194'
spec:
  containers:
  - name: nginx-smokeys
    image: vaibhavb007/nginx_smokeys
    ports:
    - containerPort: 80
    imagePullPolicy: IfNotPresent
